name: tpl
description: "Task Premier League - Powered by A28 Technologies"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#0F111A"
  adaptive_icon_foreground: "assets/images/logo.png"
  

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    
  
